name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy with Docker Compose
        run: |
          cd /home/golu/Desktop/webvory/fastapi-prod

          git pull origin main

          # Create .env in the correct directory
          echo "${{ secrets.ENV_FILE }}" > .env

          docker compose down
          sleep 15
          docker compose up -d --build
